import {
	Briefcase,
	ClipboardList,
	Home,
	Settings,
	User,
	SettingsIcon,
	SquareCheckBigIcon,
	Folder,
	Users,
	GalleryHorizontal,
} from "lucide-react";

export const navItems = [
	// Both sidebar and mobile
	{
		href: "/dashboard",
		label: "Dashboard",
		group: "",
		icon: Home,
		sidebar: true,
		mobile: true,
		user: true,
		admin: true,
	},
	{
		href: "/organisations",
		label: "Organisations",
		group: "",
		icon: Users,
		sidebar: true,
		mobile: true,
		user: false,
		admin: true,
	},
	{
		href: "/workspace",
		label: "Workspace",
		group: "",
		icon: Briefcase,
		sidebar: true,
		mobile: true,
		user: true,
		admin: false,
	},
	{
		href: "/projects",
		label: "Projects",
		group: "",
		icon: Folder,
		sidebar: true,
		mobile: true,
		user: false,
		admin: true,
	},
	{
		href: "/projects/create-project",
		label: "Create New Project",
		group: "",
		icon: Folder,
		sidebar: false,
		mobile: false,
		user: false,
		admin: false,
	},
	{
		href: "/tasks",
		label: "Tasks",
		group: "",
		icon: ClipboardList,
		sidebar: true,
		mobile: true,
		user: true,
		admin: true,
	},
	{
		href: "/approvals",
		label: "Approvals",
		group: "",
		icon: SquareCheckBigIcon,
		sidebar: true,
		mobile: true,
		user: false,
		admin: true,
	},
	{
		href: "/settings",
		label: "Settings",
		group: "",
		icon: SettingsIcon,
		sidebar: true,
		mobile: false,
		user: true,
		admin: true,
	},
	{
		href: "/statistics",
		label: "Statistics",
		group: "",
		icon: GalleryHorizontal,
		sidebar: true,
		mobile: true,
		user: false,
		admin: true,
	},

	// Sidebar only
	// Mobile only
	{
		href: "/profile",
		label: "Profile",
		group: "",
		icon: User,
		sidebar: false,
		mobile: true,
		user: true,
		admin: true,
	},
	// None
	{
		href: "/settings",
		label: "Settings",
		group: "",
		icon: Settings,
		sidebar: false,
		mobile: false,
		user: true,
		admin: true,
	},
];
