import type { ProjectTypeDefinition, ProjectTypeId } from "./types";

export const PROJECT_TYPES: ProjectTypeDefinition[] = [
	// Residential — Priority A
	{
		id: "R1",
		label: "Single-family villa / bungalow",
		group: "Residential",
		priority: "A",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 2200,
	},
	{
		id: "R2",
		label: "Row houses / townhouses",
		group: "Residential",
		priority: "A",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 2000,
	},
	{
		id: "R3",
		label: "Low-rise apartments (G+2–4)",
		group: "Residential",
		priority: "A",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 2100,
	},
	{
		id: "R4",
		label: "Mid-rise residential (G+5–12)",
		group: "Residential",
		priority: "A",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 2400,
	},
	{
		id: "R5",
		label: "High-rise residential tower",
		group: "Residential",
		priority: "A",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 2800,
	},
	{
		id: "R8",
		label: "Farmhouse / weekend home",
		group: "Residential",
		priority: "A",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 1900,
	},
	// Residential — Priority B
	{
		id: "R6",
		label: "Affordable housing / EWS–LIG",
		group: "Residential",
		priority: "B",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 1600,
	},
	{
		id: "R7",
		label: "Senior living",
		group: "Residential",
		priority: "B",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 2300,
	},
	{
		id: "R9",
		label: "Flat interior renovation",
		group: "Residential renovation",
		priority: "B",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 1200,
	},
	{
		id: "R10",
		label: "Full home renovation",
		group: "Residential renovation",
		priority: "B",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 1500,
	},
	{
		id: "R11",
		label: "Structural retrofit",
		group: "Residential renovation",
		priority: "B",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 1400,
	},
	// Commercial — A
	{
		id: "C1",
		label: "Office building",
		group: "Commercial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 3200,
	},
	{
		id: "C2",
		label: "IT park / campus",
		group: "Commercial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 3400,
	},
	{
		id: "C3",
		label: "Retail strip / mall",
		group: "Commercial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 3000,
	},
	{
		id: "C4",
		label: "Shopping complex",
		group: "Commercial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 3100,
	},
	{
		id: "C5",
		label: "Hotel / hospitality",
		group: "Commercial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 4500,
	},
	{
		id: "C6",
		label: "Restaurant / QSR fit-out",
		group: "Commercial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 2800,
	},
	{
		id: "C7",
		label: "Cinema / multiplex",
		group: "Commercial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 3800,
	},
	// Commercial — B
	{
		id: "C8",
		label: "Co-working",
		group: "Commercial",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 2600,
	},
	{
		id: "C9",
		label: "Shell-and-core only",
		group: "Commercial fit-out",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 1800,
	},
	{
		id: "C10",
		label: "Tenant office fit-out",
		group: "Commercial fit-out",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 2200,
	},
	{
		id: "C11",
		label: "Retail fit-out",
		group: "Commercial fit-out",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 2400,
	},
	// Mixed-use — A
	{
		id: "M2",
		label: "Residential + office",
		group: "Mixed-use",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 3000,
	},
	{
		id: "M3",
		label: "Township / plotted development",
		group: "Mixed-use",
		priority: "A",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 2000,
	},
	{
		id: "M1",
		label: "Residential + retail podium",
		group: "Mixed-use",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 2600,
	},
	// Industrial — A
	{
		id: "I1",
		label: "Warehouse / logistics",
		group: "Industrial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 1400,
	},
	{
		id: "I2",
		label: "Factory / manufacturing",
		group: "Industrial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 1800,
	},
	{
		id: "I3",
		label: "Cold storage",
		group: "Industrial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 2200,
	},
	{
		id: "I4",
		label: "Industrial shed",
		group: "Industrial",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 1200,
	},
	{
		id: "I5",
		label: "Industrial renovation",
		group: "Industrial",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 1100,
	},
	// Institutional — A
	{
		id: "N1",
		label: "School / college",
		group: "Institutional",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 2600,
	},
	{
		id: "N2",
		label: "Hospital / clinic",
		group: "Institutional",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 4200,
	},
	{
		id: "N3",
		label: "Religious building",
		group: "Institutional",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 2400,
	},
	{
		id: "N4",
		label: "Community hall",
		group: "Institutional",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 2200,
	},
	{
		id: "N5",
		label: "Government building",
		group: "Institutional",
		priority: "A",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 3000,
	},
	// Infrastructure — B
	{
		id: "S1",
		label: "Roads (internal / colony)",
		group: "Infrastructure",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 800,
	},
	{
		id: "S2",
		label: "Drainage / STP",
		group: "Infrastructure",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 600,
	},
	{
		id: "S3",
		label: "Boundary wall / gate",
		group: "Infrastructure",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 500,
	},
	{
		id: "S4",
		label: "Landscaping / hardscape",
		group: "Infrastructure",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 400,
	},
	{
		id: "S5",
		label: "Solar / rooftop works",
		group: "Infrastructure",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 700,
	},
	// Other — B
	{
		id: "O1",
		label: "Interior-only (no civil)",
		group: "Other",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 1000,
	},
	{
		id: "O2",
		label: "Structural repair",
		group: "Other",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 900,
	},
	{
		id: "O3",
		label: "Demolition + rebuild",
		group: "Other",
		priority: "B",
		legacyCategory: "Residential",
		defaultBenchmarkPerSqft: 2000,
	},
	{
		id: "O4",
		label: "Custom / other",
		group: "Other",
		priority: "B",
		legacyCategory: "Commercial",
		defaultBenchmarkPerSqft: 2000,
	},
];

const byId = new Map(PROJECT_TYPES.map((t) => [t.id, t]));

export function getProjectType(id: ProjectTypeId | string): ProjectTypeDefinition | undefined {
	return byId.get(id as ProjectTypeId);
}

export function projectTypeGroups(): { group: string; types: ProjectTypeDefinition[] }[] {
	const map = new Map<string, ProjectTypeDefinition[]>();
	for (const t of PROJECT_TYPES) {
		const list = map.get(t.group) ?? [];
		list.push(t);
		map.set(t.group, list);
	}
	return Array.from(map.entries()).map(([group, types]) => ({ group, types }));
}
